[package]
name = "fyc-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
fyc-db = { path = "../fyc-db" }
librage = { git = "https://github.com/mroczect/librage.git" }
argon2 = "0.5"
sha2 = "0.10"
getrandom = "0.2"
thiserror = "2"
zeroize = { version = "1", features = ["derive"] }
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }