[package]
name = "fyc-server"
version = "0.2.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-rt = "2"
fyc-sdk = { path = "../fyc-sdk" }
fyc-db = { path = "../fyc-db", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tempfile = "3"