[package]
name = "app_fyc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[[bin]]
name = "init_example"
path = "src/init_example.rs"

[[bin]]
name = "db_view"
path = "src/db_view.rs"

[dependencies]
lib_fyc_db = { path = "../lib_fyc_db" }
lib_fyc_crypto = { path = "../lib_fyc_crypto" }
lib_fyc_account = { path = "../lib_fyc_account" }
lib_fyc_role = { path = "../lib_fyc_role" }
zeroize = "1"
rand = "0.8"
tracing-subscriber = "0.3"
rpassword = "7"   
postcard = "1"
hex = "0.4"